services:
  barbania-customer-portal:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.barbania.rule=Host(`portal.barbania.com`)"
      - "traefik.http.routers.barbania.entrypoints=web,websecure"
      - "traefik.http.routers.barbania.tls.certresolver=letsencrypt"
      - "traefik.http.services.barbania.loadbalancer.server.port=3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true